#!/usr/bin/env python

#-----------------------------------------------------------------------
# api.py
# Authors: Gregory McCord and Christopher McCord
#-----------------------------------------------------------------------

import time

from flask import Flask, jsonify

#-----------------------------------------------------------------------

app = Flask(__name__,
            template_folder='.',
            static_url_path='',
            static_folder='mass-tickets-app/build')

# Generated by os.urandom(16)
app.secret_key = b'\x175^\xcf\x823h\xe5\xf1v\xa45\xd7[<9'

#-----------------------------------------------------------------------

@app.route('/')
def root():
    print('index')
    return app.send_static_file('index.html')

@app.route('/time', methods=['GET'])
def get_current_time():
    print('test')
    return jsonify(time=time.time())

# Main function
def main():

    # Do stuff
    app.run(host='0.0.0.0', debug=True)
    
#-----------------------------------------------------------------------

if __name__ == '__main__':
    main()